<?php

namespace SASLdap\Tests;

use PHPUnit\Framework\TestCase;

class SASLdapAuthenticateTest extends TestCase
{
    function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
